version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - infra
 
networks:
  infra:
    name: 'infra'
    driver: bridge
 
volumes:
  postgres:
    name: postgres